(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> redirect() got an unexpected keyword argument 'vars'"
p3
sS'layer'
p4
S'/home/marvin/lib/python/web2py/applications/TRVLR/controllers/create_profile.py'
p5
sS'code'
p6
S"# -*- coding: utf-8 -*-\n# try something like\ndef index():\n    form = SQLFORM.factory(Field('first_Name', requires=IS_NOT_EMPTY()),\n                          Field('second_Name', requires=IS_NOT_EMPTY()),\n                          Field('gender', requires=IS_NOT_EMPTY()),\n                          Field('location', requires=IS_NOT_EMPTY()),\n                          Field('age', requires=IS_NOT_EMPTY()),\n                          Field('birth_date', 'date')).process()\n    if form.accepted:\n        redirect(URL('created'), vars={'first_name':form.vars.first_name})\n    elif form.errors:\n        response.flash = 'try again the page has missing fields.'\n    return locals()\n\ndef created():\n    return dict(accepted='Your profile has been created')\n\nresponse._vars=response._caller(index)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/marvin/lib/python/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/marvin/lib/python/web2py/applications/TRVLR/controllers/create_profile.py", line 19, in <module>\n  File "/home/marvin/lib/python/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/marvin/lib/python/web2py/applications/TRVLR/controllers/create_profile.py", line 11, in index\n    redirect(URL(\'created\'), vars={\'first_name\':form.vars.first_name})\nTypeError: redirect() got an unexpected keyword argument \'vars\'\n'
p11
s.